// src/data/ejerciciosDisponibles.js
const ejerciciosDisponibles = [
  { id: '1', name: 'Press de Banca', image: require('../../assets/images/pressdebanca.gif'), muscles: ['Pechos'] },
  { id: '2', name: 'Sentadilla', image: require('../../assets/images/sentadilla.gif'), muscles: ['Cuadriceps'] },
  { id: '3', name: 'Peso Muerto', image: require('../../assets/images/pesomuerto.gif'), muscles: ['Espalda', 'Femorales'] },
  { id: '4', name: 'Curl de Bíceps', image: require('../../assets/images/curldbiceps.gif'), muscles: ['Bíceps'] },
  { id: '5', name: 'Extensiones de Pierna', image: require('../../assets/images/extensionespierna.gif'), muscles: ['Cuadriceps'] },
  { id: '6', name: 'Sentadilla Hack', image: require('../../assets/images/hacksquat.gif'), muscles: ['Cuadriceps'] },
  { id: '7', name: 'Prensa', image: require('../../assets/images/leg-press.gif'), muscles: ['Cuadriceps'] },
  { id: '8', name: 'Sentadilla Smith', image: require('../../assets/images/smithsquat.gif'), muscles: ['Cuadriceps'] },
  { id: '9', name: 'Cama Flexora', image: require('../../assets/images/leg-curl.gif'), muscles: ['Femorales'] },
  { id: '10', name: 'Press Inclinado', image: require('../../assets/images/inclinedpress.gif'), muscles: ['Pechos'] },
  { id: '11', name: 'Press con Mancuernas', image: require('../../assets/images/dumbellpress.gif'), muscles: ['Pechos'] },
  { id: '12', name: 'Press Inclinado con Mancuernas', image: require('../../assets/images/inclineddumbell.gif'), muscles: ['Pechos'] },
  { id: '13', name: 'Extensión de Tríceps', image: require('../../assets/images/triceps-pushdown.gif'), muscles: ['Tríceps'] },
  { id: '14', name: 'Extensión sobre la Nuca', image: require('../../assets/images/overheadtricep.gif'), muscles: ['Tríceps'] },
  { id: '15', name: 'Fondos', image: require('../../assets/images/fondos.gif'), muscles: ['Tríceps', 'Pechos'] },
  { id: '16', name: 'Jalón al Pecho', image: require('../../assets/images/jalon.gif'), muscles: ['Espalda'] },
  { id: '17', name: 'Remo con Barra', image: require('../../assets/images/barbellrow.gif'), muscles: ['Espalda'] },
  { id: '18', name: 'Remo con Mancuernas', image: require('../../assets/images/dumbellrow.gif'), muscles: ['Espalda'] },
  { id: '19', name: 'Remo en T', image: require('../../assets/images/remotgif.gif'), muscles: ['Espalda'] },
  { id: '20', name: 'Elevación de Pantorrillas', image: require('../../assets/images/standingcalfraise.gif'), muscles: ['Pantorrillas'] },
  { id: '21', name: 'Elevación de Pantorrillas Sentado', image: require('../../assets/images/calfraise.gif'), muscles: ['Pantorrillas'] },
  { id: '22', name: 'Press Militar', image: require('../../assets/images/barbell-military-press.gif'), muscles: ['Hombros'] },
  { id: '23', name: 'Press Militar con Mancuernas', image: require('../../assets/images/Dumbbell-Shoulder-Press.gif'), muscles: ['Hombros'] },
  { id: '24', name: 'Hip Thrust', image: require('../../assets/images/Hip-Thrust.gif'), muscles: ['Glúteos'] },
  { id: '25', name: 'Patada de Glúteo', image: require('../../assets/images/glute-kickback.gif'), muscles: ['Glúteos'] },
  { id: '26', name: 'Sentadillas Búlgaras', image: require('../../assets/images/bulgarian.gif'), muscles: ['Cuadriceps', 'Glúteos'] },
  { id: '27', name: 'Curl Martillo', image: require('../../assets/images/hammercurl.gif'), muscles: ['Bíceps'] },
  { id: '28', name: 'Curl Unilateral Mancuerna', image: require('../../assets/images/curl-alternado.gif'), muscles: ['Bíceps'] },
  { id: '29', name: 'Curl Predicador', image: require('../../assets/images/curl-scott.gif'), muscles: ['Bíceps'] },
  { id: '30', name: 'Pullover', image: require('../../assets/images/Pullover.gif'), muscles: ['Pechos', 'Espalda'] },
  { id: '31', name: 'Apertura de Pecho', image: require('../../assets/images/chestfly.gif'), muscles: ['Pechos'] },
  { id: '32', name: 'Elevaciones Laterales', image: require('../../assets/images/lateralraises.gif'), muscles: ['Hombros'] },
  { id: '33', name: 'Abdominales', image: require('../../assets/images/Cross-Crunch.gif'), muscles: ['Abdomen'] },
  { id: '34', name: 'Encogimiento de Hombros', image: require('../../assets/images/shrugs.gif'), muscles: ['Hombros'] },
  { id: '34', name: 'Press Francés', image: require('../../assets/images/frenchpress.gif'), muscles: ['Tríceps'] },
];
  
  export default ejerciciosDisponibles;
  